#!/bin/bash

#############################
# Set HUB_WEBROOT if absent #
#############################
if [ -z "$HUB_WEBROOT" ]; then
  source ~/.bin/.env
  export HUB_WEBROOT=$PROD_WEBROOT
fi

if [ $1 == 'dev' ]; then
  export HUB_WEBROOT=$DEV_WEBROOT
fi

######################
# Run correct script #
######################
case "$1" in
	cd)
		. ~/.bin/hub_cd "$@"
		;;
	errors)
		. ~/.bin/hub_errors "$@"
		;;
	mysql)
		. ~/.bin/hub_mysql "$@"
		;;
esac
