#!/bin/bash

#######################
# Load .env if needed #
#######################
if [ -z "$HZ_BASH_ENV_LOADED" ]; then
  source ~/.bin/.env
fi

######################
# Run correct script #
######################
case "$1" in
  cd)
    script=cd
    ;;
  db)
    script=access_hub_db
    ;;
  db_to_csv)
    script=export_to_csv
    ;;
  errors)
    script=tail_error_log
    ;;
  permissions)
    script=fix_fs_permissions
    ;;
esac

. ~/.bin/$script "$@"
