#!/bin/bash

######################
# Run correct script #
######################
case "$1" in
  cd)
    command=~/.bin/hub_cd
    ;;
  db)
    command=~/.bin/hub_db
    ;;
  errors)
    command=~/.bin/hub_errors
    ;;
  *)
    command=~/.bin/hub_set_env
    ;;
esac

. $command "$@"
