#!/bin/bash

source ~/.bin/.env

case $1 in
  dev)
    webroot=$DEV_WEBROOT
    ;;
  qa)
    webroot=$QA_WEBROOT
    ;;
  stage)
    webroot=$STAGE_WEBROOT
    ;;
  '')
    webroot=$PROD_WEBROOT
    ;;
esac

export HUB_WEBROOT=$webroot
